/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Employee Attendance Management System API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type RegisterInputRole = typeof RegisterInputRole[keyof typeof RegisterInputRole];


export const RegisterInputRole = {
  admin: 'admin',
  employee: 'employee',
} as const;

export interface RegisterInput {
  /** @minLength 2 */
  name: string;
  email: string;
  /** @minLength 6 */
  password: string;
  role?: RegisterInputRole;
}

export interface LoginInput {
  email: string;
  password: string;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  admin: 'admin',
  employee: 'employee',
  manager: 'manager',
} as const;

export interface User {
  id: number;
  name: string;
  email: string;
  role: UserRole;
  /** @nullable */
  department?: string | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  workHoursPerDay?: number;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export interface ChangePasswordInput {
  currentPassword: string;
  /** @minLength 6 */
  newPassword: string;
}

export type UserInputRole = typeof UserInputRole[keyof typeof UserInputRole];


export const UserInputRole = {
  admin: 'admin',
  employee: 'employee',
} as const;

export interface UserInput {
  name: string;
  email: string;
  password: string;
  role: UserInputRole;
  department?: string;
  position?: string;
  phone?: string;
  workHoursPerDay?: number;
}

export interface UserUpdate {
  name?: string;
  department?: string;
  position?: string;
  phone?: string;
  workHoursPerDay?: number;
}

export interface Location {
  id: number;
  name: string;
  address: string;
  /** @nullable */
  lat?: number | null;
  /** @nullable */
  lng?: number | null;
  createdAt: string;
}

export interface LocationInput {
  name: string;
  address: string;
  lat?: number;
  lng?: number;
}

export interface LocationUpdate {
  name?: string;
  address?: string;
  lat?: number;
  lng?: number;
}

export type AttendanceRecordStatus = typeof AttendanceRecordStatus[keyof typeof AttendanceRecordStatus];


export const AttendanceRecordStatus = {
  present: 'present',
  late: 'late',
  early_leave: 'early_leave',
  absent: 'absent',
  on_leave: 'on_leave',
} as const;

export interface AttendanceRecord {
  id: number;
  userId: number;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  locationId?: number | null;
  /** @nullable */
  locationName?: string | null;
  date: string;
  checkIn: string;
  /** @nullable */
  checkOut?: string | null;
  /** @nullable */
  hoursWorked?: number | null;
  /** @nullable */
  overtime?: number | null;
  status: AttendanceRecordStatus;
  /** @nullable */
  notes?: string | null;
  biometricVerified?: boolean;
  createdAt: string;
}

export interface CheckInInput {
  locationId: number;
  biometricVerified?: boolean;
  notes?: string;
}

export interface CheckOutInput {
  notes?: string;
}

export interface AttendanceUpdate {
  checkIn?: string;
  checkOut?: string;
  status?: string;
  notes?: string;
}

export interface DailySummary {
  date: string;
  totalEmployees: number;
  present: number;
  absent: number;
  late: number;
  onLeave: number;
  totalHours: number;
}

export interface MonthlySummary {
  month: number;
  year: number;
  userId: number;
  totalDays: number;
  presentDays: number;
  absentDays: number;
  leaveDays: number;
  totalHours: number;
  overtime: number;
  avgHoursPerDay: number;
}

export type LeaveRequestType = typeof LeaveRequestType[keyof typeof LeaveRequestType];


export const LeaveRequestType = {
  annual: 'annual',
  sick: 'sick',
  emergency: 'emergency',
  unpaid: 'unpaid',
} as const;

export type LeaveRequestStatus = typeof LeaveRequestStatus[keyof typeof LeaveRequestStatus];


export const LeaveRequestStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
  cancelled: 'cancelled',
} as const;

export interface LeaveRequest {
  id: number;
  userId: number;
  /** @nullable */
  userName?: string | null;
  type: LeaveRequestType;
  startDate: string;
  endDate: string;
  totalDays?: number;
  /** @nullable */
  reason?: string | null;
  status: LeaveRequestStatus;
  /** @nullable */
  reviewedBy?: number | null;
  /** @nullable */
  reviewedAt?: string | null;
  createdAt: string;
}

export type LeaveInputType = typeof LeaveInputType[keyof typeof LeaveInputType];


export const LeaveInputType = {
  annual: 'annual',
  sick: 'sick',
  emergency: 'emergency',
  unpaid: 'unpaid',
} as const;

export interface LeaveInput {
  type: LeaveInputType;
  startDate: string;
  endDate: string;
  reason?: string;
}

export type LeaveUpdateStatus = typeof LeaveUpdateStatus[keyof typeof LeaveUpdateStatus];


export const LeaveUpdateStatus = {
  approved: 'approved',
  rejected: 'rejected',
  cancelled: 'cancelled',
} as const;

export interface LeaveUpdate {
  status?: LeaveUpdateStatus;
  reason?: string;
}

export type AttendanceReportSummary = {
  totalDays: number;
  totalHours: number;
  overtime: number;
  presentDays: number;
  absentDays: number;
};

export interface AttendanceReport {
  from: string;
  to: string;
  records: AttendanceRecord[];
  summary: AttendanceReportSummary;
}

export interface DashboardStats {
  totalEmployees: number;
  presentToday: number;
  absentToday: number;
  onLeaveToday: number;
  lateToday: number;
  pendingLeaves: number;
  totalHoursThisMonth: number;
  avgAttendanceRate: number;
  recentActivity?: AttendanceRecord[];
}

export type UserSettingsTheme = typeof UserSettingsTheme[keyof typeof UserSettingsTheme];


export const UserSettingsTheme = {
  light: 'light',
  dark: 'dark',
  system: 'system',
} as const;

export type UserSettingsFontSize = typeof UserSettingsFontSize[keyof typeof UserSettingsFontSize];


export const UserSettingsFontSize = {
  small: 'small',
  medium: 'medium',
  large: 'large',
} as const;

export type UserSettingsLanguage = typeof UserSettingsLanguage[keyof typeof UserSettingsLanguage];


export const UserSettingsLanguage = {
  ar: 'ar',
  en: 'en',
  sv: 'sv',
} as const;

export interface UserSettings {
  userId: number;
  theme: UserSettingsTheme;
  fontSize: UserSettingsFontSize;
  language: UserSettingsLanguage;
}

export type UserSettingsUpdateTheme = typeof UserSettingsUpdateTheme[keyof typeof UserSettingsUpdateTheme];


export const UserSettingsUpdateTheme = {
  light: 'light',
  dark: 'dark',
  system: 'system',
} as const;

export type UserSettingsUpdateFontSize = typeof UserSettingsUpdateFontSize[keyof typeof UserSettingsUpdateFontSize];


export const UserSettingsUpdateFontSize = {
  small: 'small',
  medium: 'medium',
  large: 'large',
} as const;

export type UserSettingsUpdateLanguage = typeof UserSettingsUpdateLanguage[keyof typeof UserSettingsUpdateLanguage];


export const UserSettingsUpdateLanguage = {
  ar: 'ar',
  en: 'en',
  sv: 'sv',
} as const;

export interface UserSettingsUpdate {
  theme?: UserSettingsUpdateTheme;
  fontSize?: UserSettingsUpdateFontSize;
  language?: UserSettingsUpdateLanguage;
}

export type AiMessageConversationHistoryItemRole = typeof AiMessageConversationHistoryItemRole[keyof typeof AiMessageConversationHistoryItemRole];


export const AiMessageConversationHistoryItemRole = {
  user: 'user',
  assistant: 'assistant',
} as const;

export type AiMessageConversationHistoryItem = {
  role: AiMessageConversationHistoryItemRole;
  content: string;
};

export interface AiMessage {
  message: string;
  conversationHistory?: AiMessageConversationHistoryItem[];
}

export interface AiReply {
  reply: string;
}

export type ListUsersParams = {
search?: string;
role?: string;
};

export type ListAttendanceParams = {
userId?: number;
from?: string;
to?: string;
status?: string;
};

export type GetDailySummaryParams = {
date?: string;
userId?: number;
};

export type GetMonthlySummaryParams = {
month?: number;
year?: number;
userId?: number;
};

export type ListLeaveParams = {
userId?: number;
status?: string;
from?: string;
to?: string;
};

export type GetAttendanceReportParams = {
from: string;
to: string;
userId?: number;
};

